IoT/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from slews import views


urlpatterns = [
    url(r'^$',views.main,name='main'),
    # url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^slews/',include('slews.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'index/',views.index,name='index'),
    # url(r'main/',views.main,name='main'),
]

slews/urls.py
from django.conf.urls import url
from slews import views

app_name = 'slews'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^main/$',views.main,name='main'),
    url(r'^dashboardslews/$',views.dashboard,name='dashboard')
]

slews/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)

    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

slews/forms.py
from cProfile import label
from django import forms
from django.contrib.auth.models import User
from slews.models import UserProfileInfo

class UserForm(forms.ModelForm):
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}))

    class Meta():
        model = User
        fields = ('username','email','password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'required': True}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'type': 'email'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'type':'password'}),
        }
        help_texts = {
            'username' : None,
        }

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')
        widgets = {
            'portfolio_site': forms.TextInput(attrs={'class': 'form-control mb-4'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control-file', 'id': 'customFile', 'type':'file', 'data-browse-on-zone-click': 'True'}),
        }
        labels = {
            'profile_pic': 'Profile Picture'
        }

slews/views.py
from enum import auto
from http import client
from django.shortcuts import render
from slews.forms import UserForm,UserProfileInfoForm
from slews import influxcon

from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings

import json
import folium

# m = folium.Map(width=800, height=500, location=[6.9214, 122.0490])

# Create your views here.
def index(request):
    return render(request,'slews/index.html')

def main(request):
    slewsmap = folium.Map(location=[7.038800, 122.100025], zoom_start=12, tiles="cartodbpositron",
               scrollWheelZoom=False)

    acceV = get_accelerometer('SELECT mean(value) FROM device_frmpayload_data_Accelerometer WHERE (dev_eui = \'b02fd62ef52074de\') AND time >= now() - 1h and time <= now() GROUP BY time(5s) fill(null)')
    incliV = get_gyro('SELECT mean(value) FROM device_frmpayload_data_Gyro WHERE (dev_eui = \'b02fd62ef52074de\') AND time >= now() - 1h and time <= now() GROUP BY time(5s) fill(null)')
    soilV = get_soilm('SELECT mean(value) FROM device_frmpayload_data_SoilMoisture WHERE (dev_eui = \'b02fd62ef52074de\') AND time >= now() - 1h and time <= now() GROUP BY time(5s) fill(null)')
    tempV = get_temperature('SELECT mean(value) FROM device_frmpayload_data_Temperature WHERE (dev_eui = \'b02fd62ef52074de\') AND time >= now() - 1h and time <= now() GROUP BY time(5s) fill(null)')


    folium.Marker([7.12634318821439, 121.9271515462821], tooltip='Click to see details', popup="Accelerometer: " + '{:.2f}'.format(acceV) +
                                    "<br> Inclinometer: " + '{:.2f}'.format(incliV) + "<br> Soil Moisture: " + '{:.2f}'.format(soilV) +
                                    "<br> Temperature: " + '{:.2f}'.format(tempV),
                                    icon=folium.Icon(color='green')).add_to(slewsmap)


    # folium.Marker([7.12634318821439, 121.9271515462821], tooltip='Click to see details', popup="Rating: 63% Warning<br>Soil moisture: 52% <br>Movement:4m2",
    #                 icon=folium.Icon(color='red')).add_to(m)
    # folium.Marker([7.1286123128787136, 121.9294096569382], tooltip='Click to see details', popup="Rating: 63% Warning<br>Soil moisture: 52% <br>Movement:4m2",
    #                 icon=folium.Icon(color='orange')).add_to(m)
    # folium.Marker([7.128935217462367, 121.93124274798035], tooltip='Click to see details', popup="Rating: 63% Warning<br>Soil moisture: 52% <br>Movement:4m2",
    #                 icon=folium.Icon(color='red')).add_to(m)
    slewsmap = slewsmap._repr_html_()

    return render(request,'slews/main.html',{
                                'slewsmap':slewsmap
    })

@login_required
def dashboard(request):

    # nodeAccelerometer = list(influxcon.get_influxdb_client().query('SELECT mean(value) FROM device_frmpayload_data_Accelerometer WHERE time >= now() - 6h GROUP BY time(10m) fill(linear)'))
    # nodeGyro = list(influxcon.get_influxdb_client().query('SELECT mean(value) FROM device_frmpayload_data_Gyro WHERE time >= now() - 6h GROUP BY time(10m) fill(linear)'))
    # nodeSoil = list(influxcon.get_influxdb_client().query('SELECT mean(value) FROM device_frmpayload_data_SoilMoisture WHERE time >= now() - 6h GROUP BY time(10m) fill(linear)'))
    # nodeTemperature = list(influxcon.get_influxdb_client().query('SELECT mean(value) FROM device_frmpayload_data_Temperature WHERE time >= now() - 6h GROUP BY time(10m) fill(linear)'))
    # nodeTemperatureGauge = list(influxcon.get_influxdb_client().query('SELECT mean(value) FROM device_frmpayload_data_Temperature WHERE time >= now() - 30m GROUP BY dev_eui'))
    # nodeSoilGauge = list(influxcon.get_influxdb_client().query('SELECT mean(value) FROM device_frmpayload_data_SoilMoisture WHERE time >= now() - 30m GROUP BY dev_eui'))

    # print(nodeSoilGauge[0])
    # for item in nodeSoilGauge:
    #     for data_item in item:
    #         print(data_item['mean'])

    # nodeAc = json.dumps(nodeAccelerometer)
    # nodeGy = json.dumps(nodeGyro)
    # nodeSo = json.dumps(nodeSoil)
    # nodeTe = json.dumps(nodeTemperature)
    # nodeTeG = json.dumps(nodeTemperatureGauge)
    # nodeSoG = json.dumps(nodeSoilGauge)
    #6.926468, 122.089632
    f = folium.Figure(height=500)
    armsmap = folium.Map(location=[7.127715, 121.959492], zoom_start=14, tiles="cartodbpositron",
               scrollWheelZoom=False).add_to(f)

    folium.Marker([7.12634318821439, 121.9271515462821],
                     icon=folium.Icon(color='red')).add_to(armsmap)

    folium.Marker([7.1286123128787136, 121.9294096569382],
                     icon=folium.Icon(color='green')).add_to(armsmap)
    
    folium.Marker([7.128935217462367, 121.93124274798035],
                     icon=folium.Icon(color='green')).add_to(armsmap)

    armsmap = armsmap._repr_html_()

    return render(request,'slews/dashboardslews.html',{
                                'armsmap':armsmap
    })


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method =="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'slews/registration.html',{
                            'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered
    })

def user_login(request):

    if request.method =='POST':
        email = request.POST.get('username')
        password = request.POST.get('password')
        username = get_user(email)

        user = authenticate(username=username,password=password)
        # print(user)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('main'))

            else:
                return HttpResponse('Account Not Active')

        else:
            print("Someone tried to login and failed!")
            print("Username: {} and Password: {}".format(username,password))
            return HttpResponse("invalid login details supplied!")

    else:
        return render(request,'slews/index.html',{})

def get_user(email):
    try:
        return User.objects.get(email=email.lower())
    except User.DoesNotExist:
        return None

def get_accelerometer(query):
    nodeAcc = list(influxcon.get_influxdb_client().query(query))
    acceV = 0.00
    for item in nodeAcc:
        for data_item in item:
            if data_item['mean'] is not None:
                acceV = float(data_item['mean'])
    return acceV

def get_gyro(query):
    nodeGyro = list(influxcon.get_influxdb_client().query(query))
    incliV = 0.00
    for item in nodeGyro:
        for data_item in item:
            if data_item['mean'] is not None:
                incliV = float(data_item['mean'])
    return incliV

def get_soilm(query):
    nodeSoil = list(influxcon.get_influxdb_client().query(query))
    soilV = 0.00
    for item in nodeSoil:
        for data_item in item:
            if data_item['mean'] is not None:
                soilV = float(data_item['mean'])
    return soilV

def get_temperature(query):
    nodeTemperature = list(influxcon.get_influxdb_client().query(query))
    tempV = 0.00
    for item in nodeTemperature:
        for data_item in item:
            if data_item['mean'] is not None:
                tempV = float(data_item['mean'])
    return tempV

templates/slews/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>DOST 9 IoT</title>
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/mystyle.css" %}" rel="stylesheet">
    <script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
    <!-- <script src="{% static "js/dashboard.js" %}"></script> -->
    <!-- <script src="{% static "js/gauge.js" %}"></script> -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
  </head>

  <body class="d-flex flex-column min-vh-100">

    <header class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-0 border-bottom shadow-sm" style="background-color: #2E578E;">
      <p class="h5 my-0 me-md-auto fw-normal">
        <a class="navbar-brand" href="{% url 'main' %}">
          <img src="{% static "images/masthead.png" %}" width="500" height="80" alt="">
        </a>
      </p>
      <nav class="my-2 my-md-0 me-md-3">
        <ul class="nav justify-content-end">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main' %}">Home
              <span class="box-animation">
                <span class="front">Home</span>
                <span class="back">Home</span>
              </span>
            </a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'slews:dashboard' %}">Dashboard
              <span class="box-animation">
                <span class="front">Dashboard</span>
                <span class="back">Dashboard</span>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact Us
              <span class="box-animation">
                <span class="front">Contact Us</span>
                <span class="back">Contact Us</span>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout
              <span class="box-animation">
                <span class="front">Logout</span>
                <span class="back">Logout</span>
              </span>
            </a>
          </li>
          {% else %}
          <li class="nav-item">
              <a class="nav-link" href="{% url 'slews:register' %}">Register
              <span class="box-animation">
                <span class="front">Register</span>
                <span class="back">Register</span>
              </span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'slews:user_login' %}">Login
              <span class="box-animation">
                <span class="front">Login</span>
                <span class="back">Login</span>
              </span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!-- <a class="btn btn-outline-primary" href="#">Sign up</a> -->
    </header>

    {% block body_block %}

    {% endblock %}


  </body>
  <footer class="mt-auto">
    <p class="float-end"><a href="#">Back to top</a></p>
    <p>&copy; 2021 DOST IX. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer>
</html>

templates/slews/dashboardslews.html
{% extends "slews/base.html" %}
{% load static %}
{% block body_block %}

<head>
  <link href="{% static "css/gauge.css" %}" rel="stylesheet">
</head>

<div class="container-fluid">
  <div class="row">
    <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block sidebar collapse">
      <div class="sidebar-sticky pt-3">
        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>SLEWS</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column">
          <li class="nav-item">
            <a class="nav-link active" href="#">
              <span data-feather="home"></span>
              Dashboard <span class="sr-only">(current)</span>
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              ARMS
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="shopping-cart"></span>
              Products
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="users"></span>
              Customers
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="bar-chart-2"></span>
              Reports
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="layers"></span>
              Integrations
            </a>
          </li> -->
        </ul>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>ARMS</span>
          <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
            <span data-feather="plus-circle"></span>
          </a>
        </h6>
        <ul class="nav flex-column mb-2">
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file"></span>
              Dashboard
            </a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Last quarter
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Social engagement
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <span data-feather="file-text"></span>
              Year-end sale
            </a>
          </li> -->
        </ul>
      </div>
    </nav>
    <main class="col-md-10 ms-sm-auto col-lg-10x px-md-4">
      <hr class="featurette-divider">
      <div class="container-fluid">
        {{ armsmap|safe }}
        <!-- <div class="row justify-content-cnter">
          <div class="col-sm-12 order-md-1">
            {{ armsmap|safe }}
          </div>
        </div> -->
      </div>
      <!-- <div class="d-flex justify-content-center">
        {{ armsmap|safe }}
      </div> -->
      <hr class="featurette-divider">
      <div class="row justify-content-cnter">
        <div class="col-md-6 order-md-1">
          <div class="d-flex justify-content-center">
            <iframe src="http://192.168.1.78:3000/d-solo/p_57WtBnz/slews?orgId=1&refresh=5s&theme=light&panelId=6" width="450" height="200" frameborder="0"></iframe>
          </div>
        </div>
        <div class="col-md-6 order-md-2">
          <div class="d-flex justify-content-center">
            <iframe src="http://192.168.1.78:3000/d-solo/p_57WtBnz/slews?orgId=1&theme=light&panelId=12" width="450" height="200" frameborder="0"></iframe>
          </div>
        </div>
      </div>
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-6 order-md-1">
          <iframe src="http://192.168.1.78:3000/d-solo/p_57WtBnz/slews?orgId=1&refresh=5s&theme=light&panelId=10" width="750" height="300" frameborder="0"></iframe>
        </div>
        <div class="col-md-6 order-md-2">
          <iframe src="http://192.168.1.78:3000/d-solo/p_57WtBnz/slews?orgId=1&refresh=5s&theme=light&panelId=8" width="750" height="300" frameborder="0"></iframe>
        </div>
      </div>

      <hr class="featurette-divider">
      
    </main>
    
  </div>
</div>

{% endblock %}

templates/slews/index.html
{% extends "slews/base.html" %}
{% block body_block %}
{% load static %}
<main class="px-3">
  <div class="container" id="bg">
    <div class="container-head">
      <div class="row align-items-center">
        <div class="container">
          <h1 class="display-4">SLEWS & ARMS</h1>
          <div class="row">
            <div class="col-md-4">
              <p class="lead">
                DOST IX Shallow Landslide Early Warning System & Asset and Resources Management System.</p>
            </div>
            <div class="row">
              <div class="col-md-4 align-self-end">
                <form action="{% url 'slews:user_login' %}" method="post">
                  {% csrf_token %}
                  <div class="form-group">
                      <label for="inputEmail">Email</label>
                      <input type="email" class="form-control" name="username" id="inputEmail" placeholder="Email">
                  </div>
                  <div class="form-group">
                      <label for="inputPassword">Password</label>
                      <input type="password" class="form-control" name="password" id="inputPassword" placeholder="Password">
                  </div><br>
                  <input type="submit" class="btn btn-primary" value="Login">
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/slews/registration.html
{% extends "slews/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block body_block %}

  <div class="container" id="bg">
    <div class="container-head">
      <div class="row justify-content-md-start">
        <div class="col-md-5">
          {% if registered %}
          <h1 class="display-4">Thank you for Registering!</h1>
        {% else %}
          <h1 class="display-4">Register Here!</h1>
          <p class="lead"><b>Fill out the form:</b></p>
          <hr class="featurette-divider">
          <form enctype="multipart/form-data" method="POST">
            {% csrf_token %}
            <div class="form-group mb-3">
              {% for field in user_form %}
              <div class="row mb-3">
                <label class="col-sm-4 control-label" for="{{ field.name }}">{{ field.label }} : </label>
                <div class="col-sm-8">
                  {{ field }}
                </div>
              </div>
              {% endfor %}
            </div>
            <input class="btn btn-primary mt-4" type="submit" value="Register">
          </form>
        {% endif %}
        </div>
        
      </div>
    </div>
  </div>

{% endblock %}